// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: openweathermapstore.proto

package openweathermapstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherDataRequest) Reset() {
	*x = GetWeatherDataRequest{}
	mi := &file_openweathermapstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherDataRequest) ProtoMessage() {}

func (x *GetWeatherDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherDataRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherDataRequest) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{0}
}

type Weather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Main          string                 `protobuf:"bytes,2,opt,name=Main,json=main,proto3" json:"Main,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=Icon,json=icon,proto3" json:"Icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weather) Reset() {
	*x = Weather{}
	mi := &file_openweathermapstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{1}
}

func (x *Weather) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Weather) GetMain() string {
	if x != nil {
		return x.Main
	}
	return ""
}

func (x *Weather) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Weather) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type Current struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dt            int32                  `protobuf:"varint,1,opt,name=Dt,json=dt,proto3" json:"Dt,omitempty"`
	Sunrise       int32                  `protobuf:"varint,2,opt,name=Sunrise,json=sunrise,proto3" json:"Sunrise,omitempty"`
	Sunset        int32                  `protobuf:"varint,3,opt,name=Sunset,json=sunset,proto3" json:"Sunset,omitempty"`
	Temp          float32                `protobuf:"fixed32,4,opt,name=Temp,json=temp,proto3" json:"Temp,omitempty"`
	FeelsLike     float32                `protobuf:"fixed32,5,opt,name=FeelsLike,json=feels_like,proto3" json:"FeelsLike,omitempty"`
	Pressure      int32                  `protobuf:"varint,6,opt,name=Pressure,json=pressure,proto3" json:"Pressure,omitempty"`
	Humidity      int32                  `protobuf:"varint,7,opt,name=Humidity,json=humidity,proto3" json:"Humidity,omitempty"`
	DewPoint      float32                `protobuf:"fixed32,8,opt,name=DewPoint,json=dew_point,proto3" json:"DewPoint,omitempty"`
	Uvi           float32                `protobuf:"fixed32,9,opt,name=Uvi,json=uvi,proto3" json:"Uvi,omitempty"`
	Clouds        int32                  `protobuf:"varint,10,opt,name=Clouds,json=clouds,proto3" json:"Clouds,omitempty"`
	Visibility    int32                  `protobuf:"varint,11,opt,name=Visibility,json=visibility,proto3" json:"Visibility,omitempty"`
	WindSpeed     float32                `protobuf:"fixed32,12,opt,name=WindSpeed,json=wind_speed,proto3" json:"WindSpeed,omitempty"`
	WindDeg       int32                  `protobuf:"varint,13,opt,name=WindDeg,json=wind_deg,proto3" json:"WindDeg,omitempty"`
	WindGust      float32                `protobuf:"fixed32,14,opt,name=WindGust,json=wind_gust,proto3" json:"WindGust,omitempty"`
	Weather       []*Weather             `protobuf:"bytes,15,rep,name=Weather,json=weather,proto3" json:"Weather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Current) Reset() {
	*x = Current{}
	mi := &file_openweathermapstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Current) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Current) ProtoMessage() {}

func (x *Current) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Current.ProtoReflect.Descriptor instead.
func (*Current) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{2}
}

func (x *Current) GetDt() int32 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Current) GetSunrise() int32 {
	if x != nil {
		return x.Sunrise
	}
	return 0
}

func (x *Current) GetSunset() int32 {
	if x != nil {
		return x.Sunset
	}
	return 0
}

func (x *Current) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Current) GetFeelsLike() float32 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *Current) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Current) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Current) GetDewPoint() float32 {
	if x != nil {
		return x.DewPoint
	}
	return 0
}

func (x *Current) GetUvi() float32 {
	if x != nil {
		return x.Uvi
	}
	return 0
}

func (x *Current) GetClouds() int32 {
	if x != nil {
		return x.Clouds
	}
	return 0
}

func (x *Current) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *Current) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *Current) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *Current) GetWindGust() float32 {
	if x != nil {
		return x.WindGust
	}
	return 0
}

func (x *Current) GetWeather() []*Weather {
	if x != nil {
		return x.Weather
	}
	return nil
}

type Minutely struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dt            int32                  `protobuf:"varint,1,opt,name=Dt,json=dt,proto3" json:"Dt,omitempty"`
	Precipitation float32                `protobuf:"fixed32,2,opt,name=Precipitation,json=precipitation,proto3" json:"Precipitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Minutely) Reset() {
	*x = Minutely{}
	mi := &file_openweathermapstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Minutely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Minutely) ProtoMessage() {}

func (x *Minutely) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Minutely.ProtoReflect.Descriptor instead.
func (*Minutely) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{3}
}

func (x *Minutely) GetDt() int32 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Minutely) GetPrecipitation() float32 {
	if x != nil {
		return x.Precipitation
	}
	return 0
}

type Hourly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dt            int32                  `protobuf:"varint,1,opt,name=Dt,json=dt,proto3" json:"Dt,omitempty"`
	Temp          float32                `protobuf:"fixed32,2,opt,name=Temp,json=temp,proto3" json:"Temp,omitempty"`
	FeelsLike     float32                `protobuf:"fixed32,3,opt,name=FeelsLike,json=feels_like,proto3" json:"FeelsLike,omitempty"`
	Pressure      int32                  `protobuf:"varint,4,opt,name=Pressure,json=pressure,proto3" json:"Pressure,omitempty"`
	Humidity      int32                  `protobuf:"varint,5,opt,name=Humidity,json=humidity,proto3" json:"Humidity,omitempty"`
	DewPoint      float32                `protobuf:"fixed32,6,opt,name=DewPoint,json=dew_point,proto3" json:"DewPoint,omitempty"`
	Uvi           float32                `protobuf:"fixed32,7,opt,name=Uvi,json=uvi,proto3" json:"Uvi,omitempty"`
	Clouds        int32                  `protobuf:"varint,8,opt,name=Clouds,json=clouds,proto3" json:"Clouds,omitempty"`
	Visibility    int32                  `protobuf:"varint,9,opt,name=Visibility,json=visibility,proto3" json:"Visibility,omitempty"`
	WindSpeed     float32                `protobuf:"fixed32,10,opt,name=WindSpeed,json=wind_speed,proto3" json:"WindSpeed,omitempty"`
	WindDeg       int32                  `protobuf:"varint,11,opt,name=WindDeg,json=wind_deg,proto3" json:"WindDeg,omitempty"`
	WindGust      float32                `protobuf:"fixed32,12,opt,name=WindGust,json=wind_gust,proto3" json:"WindGust,omitempty"`
	Weather       []*Weather             `protobuf:"bytes,13,rep,name=Weather,json=weather,proto3" json:"Weather,omitempty"`
	Pop           float32                `protobuf:"fixed32,14,opt,name=Pop,json=pop,proto3" json:"Pop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hourly) Reset() {
	*x = Hourly{}
	mi := &file_openweathermapstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hourly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hourly) ProtoMessage() {}

func (x *Hourly) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hourly.ProtoReflect.Descriptor instead.
func (*Hourly) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{4}
}

func (x *Hourly) GetDt() int32 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Hourly) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Hourly) GetFeelsLike() float32 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *Hourly) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Hourly) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Hourly) GetDewPoint() float32 {
	if x != nil {
		return x.DewPoint
	}
	return 0
}

func (x *Hourly) GetUvi() float32 {
	if x != nil {
		return x.Uvi
	}
	return 0
}

func (x *Hourly) GetClouds() int32 {
	if x != nil {
		return x.Clouds
	}
	return 0
}

func (x *Hourly) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *Hourly) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *Hourly) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *Hourly) GetWindGust() float32 {
	if x != nil {
		return x.WindGust
	}
	return 0
}

func (x *Hourly) GetWeather() []*Weather {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *Hourly) GetPop() float32 {
	if x != nil {
		return x.Pop
	}
	return 0
}

type Daily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dt            int32                  `protobuf:"varint,1,opt,name=Dt,json=dt,proto3" json:"Dt,omitempty"`
	Sunrise       int32                  `protobuf:"varint,2,opt,name=Sunrise,json=sunrise,proto3" json:"Sunrise,omitempty"`
	Sunset        int32                  `protobuf:"varint,3,opt,name=Sunset,json=sunset,proto3" json:"Sunset,omitempty"`
	Moonrise      int32                  `protobuf:"varint,4,opt,name=Moonrise,json=moonrise,proto3" json:"Moonrise,omitempty"`
	Moonset       int32                  `protobuf:"varint,5,opt,name=Moonset,json=moonset,proto3" json:"Moonset,omitempty"`
	MoonPhase     float32                `protobuf:"fixed32,6,opt,name=MoonPhase,json=moon_phase,proto3" json:"MoonPhase,omitempty"`
	Temp          *Temp                  `protobuf:"bytes,7,opt,name=Temp,json=temp,proto3" json:"Temp,omitempty"`
	FeelsLike     *FeelsLike             `protobuf:"bytes,8,opt,name=FeelsLike,json=feels_like,proto3" json:"FeelsLike,omitempty"`
	Pressure      int32                  `protobuf:"varint,9,opt,name=Pressure,json=pressure,proto3" json:"Pressure,omitempty"`
	Humidity      int32                  `protobuf:"varint,10,opt,name=Humidity,json=humidity,proto3" json:"Humidity,omitempty"`
	DewPoint      float32                `protobuf:"fixed32,11,opt,name=DewPoint,json=dew_point,proto3" json:"DewPoint,omitempty"`
	WindSpeed     float32                `protobuf:"fixed32,12,opt,name=WindSpeed,json=wind_speed,proto3" json:"WindSpeed,omitempty"`
	WindDeg       int32                  `protobuf:"varint,13,opt,name=WindDeg,json=wind_deg,proto3" json:"WindDeg,omitempty"`
	WindGust      float32                `protobuf:"fixed32,14,opt,name=WindGust,json=wind_gust,proto3" json:"WindGust,omitempty"`
	Weather       []*Weather             `protobuf:"bytes,15,rep,name=Weather,json=weather,proto3" json:"Weather,omitempty"`
	Clouds        int32                  `protobuf:"varint,16,opt,name=Clouds,json=clouds,proto3" json:"Clouds,omitempty"`
	Pop           float32                `protobuf:"fixed32,17,opt,name=Pop,json=pop,proto3" json:"Pop,omitempty"`
	Rain          float32                `protobuf:"fixed32,18,opt,name=Rain,json=rain,proto3" json:"Rain,omitempty"`
	Uvi           float32                `protobuf:"fixed32,19,opt,name=Uvi,json=uvi,proto3" json:"Uvi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Daily) Reset() {
	*x = Daily{}
	mi := &file_openweathermapstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Daily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Daily) ProtoMessage() {}

func (x *Daily) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Daily.ProtoReflect.Descriptor instead.
func (*Daily) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{5}
}

func (x *Daily) GetDt() int32 {
	if x != nil {
		return x.Dt
	}
	return 0
}

func (x *Daily) GetSunrise() int32 {
	if x != nil {
		return x.Sunrise
	}
	return 0
}

func (x *Daily) GetSunset() int32 {
	if x != nil {
		return x.Sunset
	}
	return 0
}

func (x *Daily) GetMoonrise() int32 {
	if x != nil {
		return x.Moonrise
	}
	return 0
}

func (x *Daily) GetMoonset() int32 {
	if x != nil {
		return x.Moonset
	}
	return 0
}

func (x *Daily) GetMoonPhase() float32 {
	if x != nil {
		return x.MoonPhase
	}
	return 0
}

func (x *Daily) GetTemp() *Temp {
	if x != nil {
		return x.Temp
	}
	return nil
}

func (x *Daily) GetFeelsLike() *FeelsLike {
	if x != nil {
		return x.FeelsLike
	}
	return nil
}

func (x *Daily) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Daily) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Daily) GetDewPoint() float32 {
	if x != nil {
		return x.DewPoint
	}
	return 0
}

func (x *Daily) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *Daily) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *Daily) GetWindGust() float32 {
	if x != nil {
		return x.WindGust
	}
	return 0
}

func (x *Daily) GetWeather() []*Weather {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *Daily) GetClouds() int32 {
	if x != nil {
		return x.Clouds
	}
	return 0
}

func (x *Daily) GetPop() float32 {
	if x != nil {
		return x.Pop
	}
	return 0
}

func (x *Daily) GetRain() float32 {
	if x != nil {
		return x.Rain
	}
	return 0
}

func (x *Daily) GetUvi() float32 {
	if x != nil {
		return x.Uvi
	}
	return 0
}

type Temp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           float32                `protobuf:"fixed32,1,opt,name=Day,json=day,proto3" json:"Day,omitempty"`
	Min           float32                `protobuf:"fixed32,2,opt,name=Min,json=min,proto3" json:"Min,omitempty"`
	Max           float32                `protobuf:"fixed32,3,opt,name=Max,json=max,proto3" json:"Max,omitempty"`
	Night         float32                `protobuf:"fixed32,4,opt,name=Night,json=night,proto3" json:"Night,omitempty"`
	Eve           float32                `protobuf:"fixed32,5,opt,name=Eve,json=eve,proto3" json:"Eve,omitempty"`
	Morn          float32                `protobuf:"fixed32,6,opt,name=Morn,json=morn,proto3" json:"Morn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temp) Reset() {
	*x = Temp{}
	mi := &file_openweathermapstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temp) ProtoMessage() {}

func (x *Temp) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temp.ProtoReflect.Descriptor instead.
func (*Temp) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{6}
}

func (x *Temp) GetDay() float32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Temp) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Temp) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Temp) GetNight() float32 {
	if x != nil {
		return x.Night
	}
	return 0
}

func (x *Temp) GetEve() float32 {
	if x != nil {
		return x.Eve
	}
	return 0
}

func (x *Temp) GetMorn() float32 {
	if x != nil {
		return x.Morn
	}
	return 0
}

type FeelsLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           float32                `protobuf:"fixed32,1,opt,name=Day,json=day,proto3" json:"Day,omitempty"`
	Night         float32                `protobuf:"fixed32,2,opt,name=Night,json=night,proto3" json:"Night,omitempty"`
	Eve           float32                `protobuf:"fixed32,3,opt,name=Eve,json=eve,proto3" json:"Eve,omitempty"`
	Morn          float32                `protobuf:"fixed32,4,opt,name=Morn,json=morn,proto3" json:"Morn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeelsLike) Reset() {
	*x = FeelsLike{}
	mi := &file_openweathermapstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeelsLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeelsLike) ProtoMessage() {}

func (x *FeelsLike) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeelsLike.ProtoReflect.Descriptor instead.
func (*FeelsLike) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{7}
}

func (x *FeelsLike) GetDay() float32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *FeelsLike) GetNight() float32 {
	if x != nil {
		return x.Night
	}
	return 0
}

func (x *FeelsLike) GetEve() float32 {
	if x != nil {
		return x.Eve
	}
	return 0
}

func (x *FeelsLike) GetMorn() float32 {
	if x != nil {
		return x.Morn
	}
	return 0
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderName    string                 `protobuf:"bytes,1,opt,name=SenderName,json=sender_name,proto3" json:"SenderName,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=Event,json=event,proto3" json:"Event,omitempty"`
	Start         int64                  `protobuf:"varint,3,opt,name=Start,json=start,proto3" json:"Start,omitempty"`
	End           int64                  `protobuf:"varint,4,opt,name=End,json=end,proto3" json:"End,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=Tags,json=tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_openweathermapstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{8}
}

func (x *Alert) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Alert) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Alert) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Alert) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetWeatherDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastUpdated    int64                  `protobuf:"varint,1,opt,name=LastUpdated,proto3" json:"LastUpdated,omitempty"`
	Lat            float32                `protobuf:"fixed32,2,opt,name=Lat,json=lat,proto3" json:"Lat,omitempty"`
	Lon            float32                `protobuf:"fixed32,3,opt,name=Lon,json=lon,proto3" json:"Lon,omitempty"`
	Timezone       string                 `protobuf:"bytes,4,opt,name=Timezone,json=timezone,proto3" json:"Timezone,omitempty"`
	TimezoneOffset int32                  `protobuf:"varint,5,opt,name=TimezoneOffset,json=timezone_offset,proto3" json:"TimezoneOffset,omitempty"`
	Current        *Current               `protobuf:"bytes,6,opt,name=Current,json=current,proto3" json:"Current,omitempty"`
	Minutely       []*Minutely            `protobuf:"bytes,7,rep,name=Minutely,json=minutely,proto3" json:"Minutely,omitempty"`
	Hourly         []*Hourly              `protobuf:"bytes,8,rep,name=Hourly,json=hourly,proto3" json:"Hourly,omitempty"`
	Daily          []*Daily               `protobuf:"bytes,9,rep,name=Daily,json=daily,proto3" json:"Daily,omitempty"`
	Alerts         []*Alert               `protobuf:"bytes,10,rep,name=Alerts,json=alerts,proto3" json:"Alerts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWeatherDataResponse) Reset() {
	*x = GetWeatherDataResponse{}
	mi := &file_openweathermapstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherDataResponse) ProtoMessage() {}

func (x *GetWeatherDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openweathermapstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherDataResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherDataResponse) Descriptor() ([]byte, []int) {
	return file_openweathermapstore_proto_rawDescGZIP(), []int{9}
}

func (x *GetWeatherDataResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *GetWeatherDataResponse) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetWeatherDataResponse) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GetWeatherDataResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GetWeatherDataResponse) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *GetWeatherDataResponse) GetCurrent() *Current {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *GetWeatherDataResponse) GetMinutely() []*Minutely {
	if x != nil {
		return x.Minutely
	}
	return nil
}

func (x *GetWeatherDataResponse) GetHourly() []*Hourly {
	if x != nil {
		return x.Hourly
	}
	return nil
}

func (x *GetWeatherDataResponse) GetDaily() []*Daily {
	if x != nil {
		return x.Daily
	}
	return nil
}

func (x *GetWeatherDataResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_openweathermapstore_proto protoreflect.FileDescriptor

const file_openweathermapstore_proto_rawDesc = "" +
	"\n" +
	"\x19openweathermapstore.proto\x12\x13openweathermapstore\"\x17\n" +
	"\x15GetWeatherDataRequest\"c\n" +
	"\aWeather\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04Main\x18\x02 \x01(\tR\x04main\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04Icon\x18\x04 \x01(\tR\x04icon\"\xac\x03\n" +
	"\aCurrent\x12\x0e\n" +
	"\x02Dt\x18\x01 \x01(\x05R\x02dt\x12\x18\n" +
	"\aSunrise\x18\x02 \x01(\x05R\asunrise\x12\x16\n" +
	"\x06Sunset\x18\x03 \x01(\x05R\x06sunset\x12\x12\n" +
	"\x04Temp\x18\x04 \x01(\x02R\x04temp\x12\x1d\n" +
	"\tFeelsLike\x18\x05 \x01(\x02R\n" +
	"feels_like\x12\x1a\n" +
	"\bPressure\x18\x06 \x01(\x05R\bpressure\x12\x1a\n" +
	"\bHumidity\x18\a \x01(\x05R\bhumidity\x12\x1b\n" +
	"\bDewPoint\x18\b \x01(\x02R\tdew_point\x12\x10\n" +
	"\x03Uvi\x18\t \x01(\x02R\x03uvi\x12\x16\n" +
	"\x06Clouds\x18\n" +
	" \x01(\x05R\x06clouds\x12\x1e\n" +
	"\n" +
	"Visibility\x18\v \x01(\x05R\n" +
	"visibility\x12\x1d\n" +
	"\tWindSpeed\x18\f \x01(\x02R\n" +
	"wind_speed\x12\x19\n" +
	"\aWindDeg\x18\r \x01(\x05R\bwind_deg\x12\x1b\n" +
	"\bWindGust\x18\x0e \x01(\x02R\twind_gust\x126\n" +
	"\aWeather\x18\x0f \x03(\v2\x1c.openweathermapstore.WeatherR\aweather\"@\n" +
	"\bMinutely\x12\x0e\n" +
	"\x02Dt\x18\x01 \x01(\x05R\x02dt\x12$\n" +
	"\rPrecipitation\x18\x02 \x01(\x02R\rprecipitation\"\x8b\x03\n" +
	"\x06Hourly\x12\x0e\n" +
	"\x02Dt\x18\x01 \x01(\x05R\x02dt\x12\x12\n" +
	"\x04Temp\x18\x02 \x01(\x02R\x04temp\x12\x1d\n" +
	"\tFeelsLike\x18\x03 \x01(\x02R\n" +
	"feels_like\x12\x1a\n" +
	"\bPressure\x18\x04 \x01(\x05R\bpressure\x12\x1a\n" +
	"\bHumidity\x18\x05 \x01(\x05R\bhumidity\x12\x1b\n" +
	"\bDewPoint\x18\x06 \x01(\x02R\tdew_point\x12\x10\n" +
	"\x03Uvi\x18\a \x01(\x02R\x03uvi\x12\x16\n" +
	"\x06Clouds\x18\b \x01(\x05R\x06clouds\x12\x1e\n" +
	"\n" +
	"Visibility\x18\t \x01(\x05R\n" +
	"visibility\x12\x1d\n" +
	"\tWindSpeed\x18\n" +
	" \x01(\x02R\n" +
	"wind_speed\x12\x19\n" +
	"\aWindDeg\x18\v \x01(\x05R\bwind_deg\x12\x1b\n" +
	"\bWindGust\x18\f \x01(\x02R\twind_gust\x126\n" +
	"\aWeather\x18\r \x03(\v2\x1c.openweathermapstore.WeatherR\aweather\x12\x10\n" +
	"\x03Pop\x18\x0e \x01(\x02R\x03pop\"\xc0\x04\n" +
	"\x05Daily\x12\x0e\n" +
	"\x02Dt\x18\x01 \x01(\x05R\x02dt\x12\x18\n" +
	"\aSunrise\x18\x02 \x01(\x05R\asunrise\x12\x16\n" +
	"\x06Sunset\x18\x03 \x01(\x05R\x06sunset\x12\x1a\n" +
	"\bMoonrise\x18\x04 \x01(\x05R\bmoonrise\x12\x18\n" +
	"\aMoonset\x18\x05 \x01(\x05R\amoonset\x12\x1d\n" +
	"\tMoonPhase\x18\x06 \x01(\x02R\n" +
	"moon_phase\x12-\n" +
	"\x04Temp\x18\a \x01(\v2\x19.openweathermapstore.TempR\x04temp\x12=\n" +
	"\tFeelsLike\x18\b \x01(\v2\x1e.openweathermapstore.FeelsLikeR\n" +
	"feels_like\x12\x1a\n" +
	"\bPressure\x18\t \x01(\x05R\bpressure\x12\x1a\n" +
	"\bHumidity\x18\n" +
	" \x01(\x05R\bhumidity\x12\x1b\n" +
	"\bDewPoint\x18\v \x01(\x02R\tdew_point\x12\x1d\n" +
	"\tWindSpeed\x18\f \x01(\x02R\n" +
	"wind_speed\x12\x19\n" +
	"\aWindDeg\x18\r \x01(\x05R\bwind_deg\x12\x1b\n" +
	"\bWindGust\x18\x0e \x01(\x02R\twind_gust\x126\n" +
	"\aWeather\x18\x0f \x03(\v2\x1c.openweathermapstore.WeatherR\aweather\x12\x16\n" +
	"\x06Clouds\x18\x10 \x01(\x05R\x06clouds\x12\x10\n" +
	"\x03Pop\x18\x11 \x01(\x02R\x03pop\x12\x12\n" +
	"\x04Rain\x18\x12 \x01(\x02R\x04rain\x12\x10\n" +
	"\x03Uvi\x18\x13 \x01(\x02R\x03uvi\"x\n" +
	"\x04Temp\x12\x10\n" +
	"\x03Day\x18\x01 \x01(\x02R\x03day\x12\x10\n" +
	"\x03Min\x18\x02 \x01(\x02R\x03min\x12\x10\n" +
	"\x03Max\x18\x03 \x01(\x02R\x03max\x12\x14\n" +
	"\x05Night\x18\x04 \x01(\x02R\x05night\x12\x10\n" +
	"\x03Eve\x18\x05 \x01(\x02R\x03eve\x12\x12\n" +
	"\x04Morn\x18\x06 \x01(\x02R\x04morn\"Y\n" +
	"\tFeelsLike\x12\x10\n" +
	"\x03Day\x18\x01 \x01(\x02R\x03day\x12\x14\n" +
	"\x05Night\x18\x02 \x01(\x02R\x05night\x12\x10\n" +
	"\x03Eve\x18\x03 \x01(\x02R\x03eve\x12\x12\n" +
	"\x04Morn\x18\x04 \x01(\x02R\x04morn\"\x9c\x01\n" +
	"\x05Alert\x12\x1f\n" +
	"\n" +
	"SenderName\x18\x01 \x01(\tR\vsender_name\x12\x14\n" +
	"\x05Event\x18\x02 \x01(\tR\x05event\x12\x14\n" +
	"\x05Start\x18\x03 \x01(\x03R\x05start\x12\x10\n" +
	"\x03End\x18\x04 \x01(\x03R\x03end\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04Tags\x18\x06 \x03(\tR\x04tags\"\xb1\x03\n" +
	"\x16GetWeatherDataResponse\x12 \n" +
	"\vLastUpdated\x18\x01 \x01(\x03R\vLastUpdated\x12\x10\n" +
	"\x03Lat\x18\x02 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03Lon\x18\x03 \x01(\x02R\x03lon\x12\x1a\n" +
	"\bTimezone\x18\x04 \x01(\tR\btimezone\x12'\n" +
	"\x0eTimezoneOffset\x18\x05 \x01(\x05R\x0ftimezone_offset\x126\n" +
	"\aCurrent\x18\x06 \x01(\v2\x1c.openweathermapstore.CurrentR\acurrent\x129\n" +
	"\bMinutely\x18\a \x03(\v2\x1d.openweathermapstore.MinutelyR\bminutely\x123\n" +
	"\x06Hourly\x18\b \x03(\v2\x1b.openweathermapstore.HourlyR\x06hourly\x120\n" +
	"\x05Daily\x18\t \x03(\v2\x1a.openweathermapstore.DailyR\x05daily\x122\n" +
	"\x06Alerts\x18\n" +
	" \x03(\v2\x1a.openweathermapstore.AlertR\x06alerts2\x86\x01\n" +
	"\x19OpenWeatherMapStoreServer\x12i\n" +
	"\x0eGetWeatherData\x12*.openweathermapstore.GetWeatherDataRequest\x1a+.openweathermapstore.GetWeatherDataResponseB[ZYgithub.com/giedrius-slegeris/proto-definitions-go/openweathermapstore;openweathermapstoreb\x06proto3"

var (
	file_openweathermapstore_proto_rawDescOnce sync.Once
	file_openweathermapstore_proto_rawDescData []byte
)

func file_openweathermapstore_proto_rawDescGZIP() []byte {
	file_openweathermapstore_proto_rawDescOnce.Do(func() {
		file_openweathermapstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openweathermapstore_proto_rawDesc), len(file_openweathermapstore_proto_rawDesc)))
	})
	return file_openweathermapstore_proto_rawDescData
}

var file_openweathermapstore_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_openweathermapstore_proto_goTypes = []any{
	(*GetWeatherDataRequest)(nil),  // 0: openweathermapstore.GetWeatherDataRequest
	(*Weather)(nil),                // 1: openweathermapstore.Weather
	(*Current)(nil),                // 2: openweathermapstore.Current
	(*Minutely)(nil),               // 3: openweathermapstore.Minutely
	(*Hourly)(nil),                 // 4: openweathermapstore.Hourly
	(*Daily)(nil),                  // 5: openweathermapstore.Daily
	(*Temp)(nil),                   // 6: openweathermapstore.Temp
	(*FeelsLike)(nil),              // 7: openweathermapstore.FeelsLike
	(*Alert)(nil),                  // 8: openweathermapstore.Alert
	(*GetWeatherDataResponse)(nil), // 9: openweathermapstore.GetWeatherDataResponse
}
var file_openweathermapstore_proto_depIdxs = []int32{
	1,  // 0: openweathermapstore.Current.Weather:type_name -> openweathermapstore.Weather
	1,  // 1: openweathermapstore.Hourly.Weather:type_name -> openweathermapstore.Weather
	6,  // 2: openweathermapstore.Daily.Temp:type_name -> openweathermapstore.Temp
	7,  // 3: openweathermapstore.Daily.FeelsLike:type_name -> openweathermapstore.FeelsLike
	1,  // 4: openweathermapstore.Daily.Weather:type_name -> openweathermapstore.Weather
	2,  // 5: openweathermapstore.GetWeatherDataResponse.Current:type_name -> openweathermapstore.Current
	3,  // 6: openweathermapstore.GetWeatherDataResponse.Minutely:type_name -> openweathermapstore.Minutely
	4,  // 7: openweathermapstore.GetWeatherDataResponse.Hourly:type_name -> openweathermapstore.Hourly
	5,  // 8: openweathermapstore.GetWeatherDataResponse.Daily:type_name -> openweathermapstore.Daily
	8,  // 9: openweathermapstore.GetWeatherDataResponse.Alerts:type_name -> openweathermapstore.Alert
	0,  // 10: openweathermapstore.OpenWeatherMapStoreServer.GetWeatherData:input_type -> openweathermapstore.GetWeatherDataRequest
	9,  // 11: openweathermapstore.OpenWeatherMapStoreServer.GetWeatherData:output_type -> openweathermapstore.GetWeatherDataResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_openweathermapstore_proto_init() }
func file_openweathermapstore_proto_init() {
	if File_openweathermapstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openweathermapstore_proto_rawDesc), len(file_openweathermapstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openweathermapstore_proto_goTypes,
		DependencyIndexes: file_openweathermapstore_proto_depIdxs,
		MessageInfos:      file_openweathermapstore_proto_msgTypes,
	}.Build()
	File_openweathermapstore_proto = out.File
	file_openweathermapstore_proto_goTypes = nil
	file_openweathermapstore_proto_depIdxs = nil
}
