// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/openweathermapstore.proto

package openweathermapstore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenWeatherMapStoreServer_GetWeatherData_FullMethodName = "/openweathermapstore.OpenWeatherMapStoreServer/GetWeatherData"
)

// OpenWeatherMapStoreServerClient is the client API for OpenWeatherMapStoreServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenWeatherMapStoreServerClient interface {
	GetWeatherData(ctx context.Context, in *GetWeatherDataRequest, opts ...grpc.CallOption) (*GetWeatherDataResponse, error)
}

type openWeatherMapStoreServerClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenWeatherMapStoreServerClient(cc grpc.ClientConnInterface) OpenWeatherMapStoreServerClient {
	return &openWeatherMapStoreServerClient{cc}
}

func (c *openWeatherMapStoreServerClient) GetWeatherData(ctx context.Context, in *GetWeatherDataRequest, opts ...grpc.CallOption) (*GetWeatherDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeatherDataResponse)
	err := c.cc.Invoke(ctx, OpenWeatherMapStoreServer_GetWeatherData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenWeatherMapStoreServerServer is the server API for OpenWeatherMapStoreServer service.
// All implementations must embed UnimplementedOpenWeatherMapStoreServerServer
// for forward compatibility.
type OpenWeatherMapStoreServerServer interface {
	GetWeatherData(context.Context, *GetWeatherDataRequest) (*GetWeatherDataResponse, error)
	mustEmbedUnimplementedOpenWeatherMapStoreServerServer()
}

// UnimplementedOpenWeatherMapStoreServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenWeatherMapStoreServerServer struct{}

func (UnimplementedOpenWeatherMapStoreServerServer) GetWeatherData(context.Context, *GetWeatherDataRequest) (*GetWeatherDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeatherData not implemented")
}
func (UnimplementedOpenWeatherMapStoreServerServer) mustEmbedUnimplementedOpenWeatherMapStoreServerServer() {
}
func (UnimplementedOpenWeatherMapStoreServerServer) testEmbeddedByValue() {}

// UnsafeOpenWeatherMapStoreServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenWeatherMapStoreServerServer will
// result in compilation errors.
type UnsafeOpenWeatherMapStoreServerServer interface {
	mustEmbedUnimplementedOpenWeatherMapStoreServerServer()
}

func RegisterOpenWeatherMapStoreServerServer(s grpc.ServiceRegistrar, srv OpenWeatherMapStoreServerServer) {
	// If the following call pancis, it indicates UnimplementedOpenWeatherMapStoreServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenWeatherMapStoreServer_ServiceDesc, srv)
}

func _OpenWeatherMapStoreServer_GetWeatherData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeatherDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenWeatherMapStoreServerServer).GetWeatherData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenWeatherMapStoreServer_GetWeatherData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenWeatherMapStoreServerServer).GetWeatherData(ctx, req.(*GetWeatherDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenWeatherMapStoreServer_ServiceDesc is the grpc.ServiceDesc for OpenWeatherMapStoreServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenWeatherMapStoreServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openweathermapstore.OpenWeatherMapStoreServer",
	HandlerType: (*OpenWeatherMapStoreServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeatherData",
			Handler:    _OpenWeatherMapStoreServer_GetWeatherData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/openweathermapstore.proto",
}
